# Generated by Django 4.2.15 on 2024-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
